name: Build


on:
  push:
   branches: 
   - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # One
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
    # Two
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check dependencies in cache 
        id: yarn-cache 
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
    # Three 
      - name: Initializing dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run:  yarn bootstrap
    # Four 
      - name: Creating & Initializing env variables for Admin Package
        run: |
          cd packages/admin
          pwd
          echo "REACT_APP_FIREBASE_API_KEY= ${{secrets.REACT_APP_FIREBASE_API_KEY}}
          REACT_APP_FIREBASE_AUTH_DOMAIN= ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_PROJECT_ID= ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET= ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID= ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FIREBASE_APP_ID= ${{secrets.REACT_APP_FIREBASE_APP_ID}}" > .env
      - name: Creating & Initializing env variables for User Package
        run: |
          cd packages/user
          pwd
          echo "REACT_APP_FIREBASE_API_KEY= ${{secrets.REACT_APP_FIREBASE_API_KEY}}
          REACT_APP_FIREBASE_AUTH_DOMAIN= ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_PROJECT_ID= ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET= ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID= ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FIREBASE_APP_ID= ${{secrets.REACT_APP_FIREBASE_APP_ID}}" > .env
    # Five 
      # - name: Run Tests 
      #   run: |
      #     yarn tests
      
      - name: Build the project
        run: |
          yarn build
    # Six 
      - name: Deploy to firebase 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEVOPS_REACT_MONOREPO_9DE22 }}'
          projectId: devops-react-monorepo-9de22
          channelId: live
